"""
Project 04 — Streamlit UI for the AI Stock Research & Investment Brief Generator.

Run:  streamlit run app.py
"""
import os
import sys

import streamlit as st
from dotenv import load_dotenv
import yfinance as yf

load_dotenv()

sys.path.insert(0, os.path.dirname(__file__))
from graph import graph  # noqa: E402

st.set_page_config(
    page_title="AI Stock Research Brief",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)
st.title("📈 AI Stock Research & Investment Brief Generator")
st.caption("Powered by LangGraph • Google Gemini • Yahoo Finance • Streamlit")
st.markdown(
    "Enter a stock ticker. Three research agents run in **parallel** (fundamentals, news sentiment, "
    "technicals), then an AI brief writer synthesizes an opinionated one-page investment brief."
)

with st.sidebar:
    st.header("Stock Lookup")
    ticker_input = st.text_input(
        "Ticker Symbol",
        placeholder="e.g. MSFT, AAPL, RELIANCE.NS",
        help="Use .NS for NSE India, .BO for BSE India",
    ).strip().upper()
    time_period = st.selectbox(
        "Chart Time Period",
        ["5d", "1mo", "3mo", "6mo", "1y"],
        index=1,
    )
    run_button = st.button("🔍 Generate Brief", type="primary", disabled=(not ticker_input))
    st.markdown("---")
    st.markdown("**Examples:** MSFT · GOOGL · TSLA · RELIANCE.NS · INFY.NS")
    refresh_data = st.checkbox(
        "Force refresh market data",
        value=False,
        help="Refresh latest data instead of using cached results.",
    )
if run_button and ticker_input:
    with st.spinner(f"Running 3 parallel research agents for **{ticker_input}**… (30–60 seconds)"):
        stock = yf.Ticker(ticker_input)
        hist = stock.history(period=time_period)

        if hist.empty:
            st.error("❌ Invalid ticker or no market data available.")
            st.stop()
        try:
            result = graph.invoke({"ticker": ticker_input})
        except Exception:
            import traceback
            st.code(traceback.format_exc())
            st.stop()

    try:
        company_name = stock.info.get("longName", ticker_input)
        sector = stock.info.get("sector", "N/A")
        industry = stock.info.get("industry", "N/A")
        high_52w = stock.info.get("fiftyTwoWeekHigh", "N/A")
        low_52w = stock.info.get("fiftyTwoWeekLow", "N/A")
        
        current_price = hist["Close"].iloc[-1]        
        st.subheader(f"🏢 {company_name}")
        st.caption(f"Sector: {sector}")
        st.caption(f"Industry: {industry}")
        st.write(f"📈 52W High: {high_52w}")
        st.write(f"📉 52W Low: {low_52w}")
        st.metric("📈 Current Stock Price", f"${current_price:.2f}")
        st.divider()
        st.subheader("📉 Stock Price Trend")
        st.line_chart(hist["Close"])
        st.caption(f"Closing price for selected period: {time_period}")
        st.write(f"📊 Total data points: {len(hist)}")
        st.write(f"📅 Date Range: {hist.index.min().date()} → {hist.index.max().date()}")
    except Exception:
        st.warning("⚠️ Company details could not be loaded.")
    # --- Investment Brief (hero section) ---
    st.success(f"Research complete for **{ticker_input}**!")
    st.toast("Research completed successfully! 🎉")
    st.balloons()
    st.subheader("📋 Investment Brief")
    st.caption("AI-generated summary based on fundamentals, news sentiment, and technical analysis.")
    st.info(f"Analyzed Stock: {ticker_input}")
    brief = result.get("investment_brief", "No brief generated.")
    st.markdown("### 🤖 AI Generated Investment Summary")
    st.markdown(brief)
    
    st.download_button(
        "📥 Download Investment Brief",
        data=brief,
        file_name=f"{ticker_input}_investment_brief.txt",
        mime="text/plain",
    )
    st.caption("Generated by AI Stock Research & Investment Brief Generator")
    st.divider()

    # --- Three specialist reports ---
    col1, col2, col3 = st.columns(3)

    with col1:
        st.subheader("🏦 Fundamentals")
        st.caption("Company financial health, valuation, and key metrics")
        st.markdown(result.get("fundamentals_report", "No report."))

    with col2:
        st.subheader("📰 News Sentiment")
        st.caption("Latest market news and AI sentiment analysis")
        st.markdown(result.get("sentiment_report", "No report."))

    with col3:
        st.subheader("📊 Technical Analysis")
        st.caption("Technical indicators, trend analysis, and momentum")
        st.markdown(result.get("technical_report", "No report."))